# Generated by Django 2.1.7 on 2019-06-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='document',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
