# Generated by Django 2.1.7 on 2019-06-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190607_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='name',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
